Traceback (most recent call last):
  File "/Users/syrkis/code/miiii/main.py", line 24, in log_run
    wandb.log({"Train Loss": train_loss}, step=range(len(train_loss)))
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 400, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 390, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1871, in log
    self._log(data=data, step=step, commit=commit)
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1635, in _log
    self._partial_history_callback(data, step, commit)
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1507, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/Users/syrkis/.pyenv/versions/3.11.7/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 615, in publish_partial_history
    partial_history.step.num = step
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'range' object cannot be interpreted as an integer